spring.datasource.url=jdbc:postgresql://localhost:5432/computer_inventory_system
spring.datasource.username=mac377
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false